const prefix = 'ProfilePartner'

export const FETCH_BEFORE = prefix + '/FETCH_BEFORE';
export const FETCH_SUCCESS = prefix + '/FETCH_SUCCESS';
export const FETCH_FAILURE = prefix + '/FETCH_FAILURE';

export const SAVE_BEFORE = prefix + '/SAVE_BEFORE';
export const SAVE_SUCCESS = prefix + '/SAVE_SUCCESS';
export const SAVE_FAILURE = prefix + '/SAVE_FAILURE';

export const UPDATE_SUBSCRIPTION_BEFORE = prefix + '/UPDATE_SUBSCRIPTION_BEFORE';
export const UPDATE_SUBSCRIPTION_SUCCESS = prefix + '/UPDATE_SUBSCRIPTION_SUCCESS';
export const UPDATE_SUBSCRIPTION_FAILURE = prefix + '/UPDATE_SUBSCRIPTION_FAILURE';

export const CANCEL_SUBSCRIPTION_BEFORE = prefix + '/CANCEL_SUBSCRIPTION_BEFORE';
export const CANCEL_SUBSCRIPTION_SUCCESS = prefix + '/CANCEL_SUBSCRIPTION_SUCCESS';
export const CANCEL_SUBSCRIPTION_FAILURE = prefix + '/CANCEL_SUBSCRIPTION_FAILURE';

export const VALIDATE_REQUEST = prefix + '/VALIDATE_REQUEST';
export const VALIDATE_SUCCESS = prefix + '/VALIDATE_SUCCESS';
export const VALIDATE_FAILURE = prefix + '/VALIDATE_FAILURE';

export const FETCH_SUBSCRIPTIONS_SUCCESS = prefix + '/FETCH_SUBSCRIPTIONS_SUCCESS';
export const FETCH_SUBSCRIPTIONS_FAILURE = prefix + '/FETCH_SUBSCRIPTIONS_FAILURE';
export const FETCH_SUBSCRIPTIONS_BEFORE = prefix + '/FETCH_SUBSCRIPTIONS_BEFORE';

export const UPLOAD_MEDIA_BEFORE = prefix + '/UPLOAD_MEDIA_BEFORE';
export const UPLOAD_MEDIA_SUCCESS = prefix + '/UPLOAD_MEDIA_SUCCESS';
export const UPLOAD_MEDIA_FAILURE = prefix + '/UPLOAD_MEDIA_FAILURE';

export const MODEL_CHANGED = prefix + '/MODEL_CHANGED';

export const ADD_POSTAL_CODE = prefix + '/ADD_POSTAL_CODE';
export const REMOVE_POSTAL_CODE = prefix + '/REMOVE_POSTAL_CODE';

export const TOGGLE_REQUESTED_CODES_MODAL = prefix + '/TOGGLE_REQUESTED_CODES_MODAL';
