security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        api_key_user_provider:
            id: App\Security\ApiKeyUserProvider
        db_provider:
            entity:
                class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # API without session. For mobile devices
        api_v1:
            pattern: ^/api/v1
            anonymous: true
            stateless: true
            entry_point: App\Security\UnauthorizedResponseHandler
            provider: api_key_user_provider

            simple_preauth:
                authenticator: App\Security\UserAuthenticator

        main:
            pattern: ^/
            anonymous: true
            stateless: false
            entry_point: App\Security\UnauthorizedResponseHandler
            json_login:
                provider: db_provider
                success_handler: App\Security\LoginSuccessHandler
                failure_handler: App\Security\LoginFailureHandler
                check_path: /api/v2/login
                username_path: login
                password_path: password
            logout:
                invalidate_session: true
                success_handler: App\Security\LogoutSuccessHandler

    access_control:
        - { path: ^/api/v1/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v2/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
