security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        api_key_user_provider:
            id: App\Security\ApiKeyUserProvider
        db_provider:
            entity:
                class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_v1:
            pattern: ^/api/v1
            anonymous: true
            stateless: true
            entry_point: App\Security\UnauthorizedResponseHandler
            provider: api_key_user_provider

            simple_preauth:
                authenticator: App\Security\UserAuthenticator

    access_control:
        - { path: ^/api/v1/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
