security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        db_provider:
            entity:
                class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            entry_point: App\Security\UnauthorizedResponseHandler
            json_login:
                provider: db_provider
                success_handler: App\Security\LoginSuccessHandler
                failure_handler: App\Security\LoginFailureHandler
                check_path: /api/v1/authenticate
                username_path: security.credentials.login
                password_path: security.credentials.password
            logout:
                invalidate_session: true
                success_handler: App\Security\LogoutSuccessHandler

    access_control:
        - { path: ^/api/v1/authenticate$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
