#!/bin/bash

docker-compose exec admin sh -c "rm -rf var/cache/test"

TEST="vendor/bin/phpunit -c . --exclude ignore $@"
#TEST="vendor/bin/paratest --functional -c . --exclude-group ignore $@"

#docker-compose exec admin phpdbg -qrr $TEST
docker-compose exec admin php $TEST
