#!/bin/bash

docker-compose exec app sh -c "rm -rf var/cache/test"

TEST="vendor/bin/phpunit -c . --exclude ignore $@"
#TEST="vendor/bin/paratest --functional -c . --exclude-group ignore $@"

#docker-compose exec app phpdbg -qrr $TEST
docker-compose exec app php $TEST
