
api_v1_categories_tree_gets:
    path: /order-categories
    methods: GET
    controller: App\Controller\CategoryRESTController::getsAction

api_v1_categories_post:
    path: /order-categories
    methods: POST
    controller: App\Controller\CategoryRESTController::postAction

api_v1_categories_put:
    path: /order-categories/{id}
    methods: PUT
    controller: App\Controller\CategoryRESTController::putAction
    requirements:
        id: \d+

api_v1_categories_delete:
    path: /order-categories/{id}
    methods: DELETE
    controller: App\Controller\CategoryRESTController::deleteAction
    requirements:
        id: \d+
