
api_v2_partners_gets:
    path: /partners
    methods: GET
    controller: App\Controller\PartnerRESTController::getsAction

api_v2_partners_get:
    path: /partners/{id}
    methods: GET
    controller: App\Controller\PartnerRESTController::getAction
    requirements:
        id: \d+

api_v2_partners_post:
    path: /partners
    methods: POST
    controller: App\Controller\PartnerRESTController::postAction

api_v2_partners_put:
    path: /partners/{id}
    methods: PUT
    controller: App\Controller\PartnerRESTController::putAction
    requirements:
        id: \d+
