
api_v1_user_locations_delete:
    path: /users/{userId}/locations/{id}
    methods: DELETE
    controller: App\Controller\UserLocationRESTController::deleteAction
    requirements:
       userId: \d+
       id: \d+

api_v1_user_locations_me_delete:
    path: /me/locations/{id}
    methods: DELETE
    controller: App\Controller\UserLocationRESTController::deleteForMeAction
    requirements:
       id: \d+
