
api_v1_orders_gets:
    path: /orders
    methods: GET
    controller: App\Controller\OrderRESTController::getsAction

api_v1_orders_get:
    path: /orders/{id}
    methods: GET
    controller: App\Controller\OrderRESTController::getAction
    requirements:
        id: \d+

api_v1_orders_post:
    path: /orders
    methods: POST
    controller: App\Controller\OrderRESTController::postAction

api_v1_orders_put:
    path: /orders/{id}
    methods: PUT
    controller: App\Controller\OrderRESTController::putAction
    requirements:
        id: \d+
