
api_v1_user_reset_password_post:
    path: /users/reset-password
    methods: POST
    controller: App\Controller\PasswordRESTController::postResetAction

api_v1_user_reset_password_put:
    path: /users/{token}/password
    methods: PUT
    controller: App\Controller\PasswordRESTController::putSetAction
    requirements:
        token: \S+