
api_v2_partner_categories_gets:
    path: /partner-categories
    methods: GET
    controller: App\Controller\PartnerCategoryRESTController::getsAction

api_v2_partner_categories_get:
    path: /partner-categories/{id}
    methods: GET
    controller: App\Controller\PartnerCategoryRESTController::getAction
    requirements:
        id: \d+

api_v2_partner_categories_post:
    path: /partner-categories
    methods: POST
    controller: App\Controller\PartnerCategoryRESTController::post

api_v2_partner_categories_put:
    path: /partner-categories/{id}
    methods: PUT
    controller: App\Controller\PartnerCategoryRESTController::put
    requirements:
        id: \d+

api_v2_partner_categories_delete:
    path: /partner-categories/{id}
    methods: DELETE
    controller: App\Controller\PartnerCategoryRESTController::remove
    requirements:
        id: \d+
