
api_v2_me_put:
    path: /me
    methods: [PUT, POST]
    controller: App\Controller\UserRESTController::putMeAction

api_v2_me_get:
    path: /me
    methods: GET
    controller: App\Controller\UserRESTController::getMeAction