users_api:
    resource: routes/users_api.yaml
    prefix: /api/v1

credit_card_api:
    resource: routes/credit_card_api.yaml
    prefix: /api/v1

media_api:
    resource: routes/media_api.yaml
    prefix: /api/v1

location_api:
    resource: routes/location_api.yaml
    prefix: /api/v1

category_api:
    resource: routes/category_api.yaml
    prefix: /api/v1/{locale}
    requirements:
        locale: '%supported_locales%'

order_api:
    resource: routes/order_api.yaml
    prefix: /api/v1

# Security

api_v1_login_post:
    path: /api/v1/login
    methods: POST
    controller: App\Controller\LoginRESTController::loginV1

api_v2_login_post:
    path: /api/v2/login
    methods: POST
    controller: App\Controller\LoginRESTController::loginV2

logout:
    path: /logout
    methods: GET
    controller: App\Controller\IndexController::logout

index:
    path: /
    methods: GET
    controller: App\Controller\IndexController::index

login:
    path: /login
    methods: GET
    controller: App\Controller\IndexController::index

categories_index:
    path: /categories
    methods: GET
    controller: App\Controller\IndexController::index

partners_index:
    path: /partners
    methods: GET
    controller: App\Controller\IndexController::index

districts_index:
    path: /districts
    methods: GET
    controller: App\Controller\IndexController::index

orders_index:
    path: /orders
    methods: GET
    controller: App\Controller\IndexController::index
