users_api:
    resource: routes/users_api.yml
    prefix: /api/v1

credit_card_api:
    resource: routes/credit_card_api.yml
    prefix: /api/v1

category_api:
    resource: routes/category_api.yml
    prefix: /api/v1/{locale}
    requirements:
        locale: '%supported_locales%'

order_api:
    resource: routes/order_api.yml
    prefix: /api/v1/{locale}
    requirements:
        locale: '%supported_locales%'