users_api:
    resource: routes/users_api.yaml
    prefix: /api/v1

credit_card_api:
    resource: routes/credit_card_api.yaml
    prefix: /api/v1

media_api:
    resource: routes/media_api.yaml
    prefix: /api/v1

location_api:
    resource: routes/location_api.yaml
    prefix: /api/v1

category_api:
    resource: routes/category_api.yaml
    prefix: /api/v1/{locale}
    requirements:
        locale: '%supported_locales%'

order_api:
    resource: routes/order_api.yaml
    prefix: /api/v1

index:
    path: /
    methods: GET
    controller: App\Controller\IndexController::index

# Security

ap1_v1_login:
    path: /api/v1/login
    methods: POST
    controller: App\Controller\LoginController::authenticate
