users_api:
    resource: routes/users_api.yml
    prefix: /api/v1

# Site pages

index:
    path: /
    methods: GET
    controller: App\Controller\IndexController::indexAction

# Security routes

login:
    path: /login
    methods: GET
    controller: App\Controller\LoginController::login

logout:
    path: /logout
    methods: GET
    controller: App\Controller\LoginController::logout

authenticate:
    path: /api/v1/authenticate
    methods: POST
    controller: App\Controller\LoginController::authenticate