parameters:
    jms_serializer.camel_case_naming_strategy.class: App\Classes\AsIsNamingStrategy
    locale: '%env(DEFAULT_LOCALE)%'
    supported_locales: '%env(SUPPORTED_LOCALES)%'
    project_host: '%env(PROJECT_HOST_SCHEMA)%://%env(PROJECT_HOST_NAME)%'
    upload_image_dir: '%env(UPLOAD_IMAGE_DIR)%'
    stripe_client_secret: '%env(STRIPE_CLIENT_SECRET)%'
    stripe_client_id: '%env(STRIPE_CLIENT_ID)%'
    payment_environment: '%env(PAYMENT_ENVIRONMENT)%'
    minimal_payment_amount: '%env(MINIMAL_PAYMENT_AMOUNT)%'
    default_country_name: '%env(DEFAULT_COUNTRY_NAME)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Symfony\Bundle\TwigBundle\Controller\ExceptionController:
        alias: twig.controller.exception
        public: true

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

# Security
    App\Security\LoginFailureHandler:
        arguments:
            $container: '@service_container'

    App\Security\LoginSuccessHandler:
        arguments:
            $container: '@service_container'

    App\Security\LogoutSuccessHandler:
        arguments:
            $container: '@service_container'

    App\Security\ApiKeyUserProvider:
        arguments:
            $container: '@service_container'

    App\Security\UnauthorizedResponseHandler:

    App\Security\UserAuthenticator:

# Public services
    App\Service\UserService:
        arguments:
            $container: '@service_container'

    App\Service\CategoryService:
        arguments:
            $container: '@service_container'

    App\Service\MediaService:
        arguments:
            $container: '@service_container'

    App\Service\OrderService:
        arguments:
            $container: '@service_container'

    App\Service\CreditCardService:
        arguments:
            $container: '@service_container'

    App\Service\LocationService:
        arguments:
            $container: '@service_container'

    App\Service\PartnerCategoryService:
        arguments:
            $container: '@service_container'

    App\Service\PartnerService:
        arguments:
            $container: '@service_container'

    App\Service\UserLocationService:
        arguments:
            $container: '@service_container'

    App\Service\DistrictService:
        arguments:
            $container: '@service_container'

    App\Service\CityService:
        arguments:
            $container: '@service_container'

    App\Service\RegionService:
        arguments:
            $container: '@service_container'

    App\Service\CountryService:
        arguments:
            $container: '@service_container'

    App\Service\PartnerPostalCodeService:
        arguments:
            $container: '@service_container'

    App\Service\PaymentService:
        arguments:
            $container: '@service_container'

# Event listeners

    App\EventSubscriber\LocaleSubscriber:
        arguments: ['%locale%']

# Commands

    App\Command\RefreshAccessTokenCommand:
        tags:
            - { name: console.command }

    App\Command\SyncPartnerCategoryCommand:
        tags:
            - { name: console.command }