ALTER TABLE categories DISABLE TRIGGER ALL;
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'junk_removal',0,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'junk_removal',0,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'junk_removal',0,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'junk_removal',0,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'junk_removal',0,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'junk_removal',0,5);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'junk_removal',0,6);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'junk_removal',0,7);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),1,'junk_removal',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),1,'junk_removal',1,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),1,'junk_removal',1,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),1,'junk_removal',1,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),1,'junk_removal',1,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),1,'junk_removal',1,5);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),1,'junk_removal',1,6);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),1,'junk_removal',1,7);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),1,'junk_removal',1,8);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),1,'junk_removal',1,9);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),1,'junk_removal',1,10);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),1,'junk_removal',1,11);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),2,'junk_removal',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),2,'junk_removal',1,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),2,'junk_removal',1,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),2,'junk_removal',1,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),24,'junk_removal',2,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),24,'junk_removal',2,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),3,'junk_removal',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),3,'junk_removal',1,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),3,'junk_removal',1,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),3,'junk_removal',1,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),3,'junk_removal',1,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),27,'junk_removal',2,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),27,'junk_removal',2,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),27,'junk_removal',2,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),27,'junk_removal',2,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),27,'junk_removal',2,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),4,'junk_removal',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),4,'junk_removal',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),4,'junk_removal',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'junk_removal',0,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'junk_removal',0,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'junk_removal',0,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'junk_removal',0,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'junk_removal',0,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'junk_removal',0,5);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'junk_removal',0,6);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'junk_removal',0,7);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),40,'junk_removal',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),40,'junk_removal',1,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),40,'junk_removal',1,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),40,'junk_removal',1,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),40,'junk_removal',1,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),40,'junk_removal',1,5);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),40,'junk_removal',1,6);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),40,'junk_removal',1,7);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),40,'junk_removal',1,8);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),40,'junk_removal',1,9);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),40,'junk_removal',1,10);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),40,'junk_removal',1,11);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),41,'junk_removal',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),41,'junk_removal',1,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),41,'junk_removal',1,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),41,'junk_removal',1,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),63,'junk_removal',2,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),63,'junk_removal',2,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),42,'junk_removal',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),42,'junk_removal',1,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),42,'junk_removal',1,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),42,'junk_removal',1,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),42,'junk_removal',1,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),66,'junk_removal',2,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),66,'junk_removal',2,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),66,'junk_removal',2,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),66,'junk_removal',2,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),66,'junk_removal',2,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),43,'junk_removal',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),43,'junk_removal',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),43,'junk_removal',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'junk_removal',0,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'junk_removal',0,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'junk_removal',0,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'junk_removal',0,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'junk_removal',0,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'junk_removal',0,5);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'junk_removal',0,6);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'junk_removal',0,7);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),79,'junk_removal',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),79,'junk_removal',1,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),79,'junk_removal',1,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),79,'junk_removal',1,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),79,'junk_removal',1,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),79,'junk_removal',1,5);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),79,'junk_removal',1,6);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),79,'junk_removal',1,7);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),79,'junk_removal',1,8);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),79,'junk_removal',1,9);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),79,'junk_removal',1,10);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),79,'junk_removal',1,11);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),80,'junk_removal',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),80,'junk_removal',1,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),80,'junk_removal',1,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),80,'junk_removal',1,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),102,'junk_removal',2,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),102,'junk_removal',2,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),81,'junk_removal',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),81,'junk_removal',1,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),81,'junk_removal',1,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),81,'junk_removal',1,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),81,'junk_removal',1,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),105,'junk_removal',2,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),105,'junk_removal',2,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),105,'junk_removal',2,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),105,'junk_removal',2,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),105,'junk_removal',2,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),82,'junk_removal',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),82,'junk_removal',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),82,'junk_removal',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,9);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,10);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),124,'recycling',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),126,'recycling',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),126,'recycling',1,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),126,'recycling',1,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),126,'recycling',1,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),126,'recycling',1,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),126,'recycling',1,5);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),126,'recycling',1,6);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,5);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,6);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,7);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,8);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,9);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,10);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),146,'recycling',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),146,'recycling',1,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),149,'recycling',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),151,'recycling',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),151,'recycling',1,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),151,'recycling',1,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),151,'recycling',1,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),151,'recycling',1,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),152,'recycling',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),152,'recycling',1,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),154,'recycling',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),154,'recycling',1,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),154,'recycling',1,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),154,'recycling',1,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),154,'recycling',1,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),154,'recycling',1,5);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),154,'recycling',1,6);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),124,'recycling',1,5);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,6);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),124,'recycling',1,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),214,'recycling',1,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),214,'recycling',1,7);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),118,'recycling',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),118,'recycling',1,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,8);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,11);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,5);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,6);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,7);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,8);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,9);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,10);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),174,'recycling',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),174,'recycling',1,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),177,'recycling',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),179,'recycling',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),179,'recycling',1,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),179,'recycling',1,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),179,'recycling',1,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),179,'recycling',1,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),180,'recycling',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),180,'recycling',1,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),182,'recycling',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),182,'recycling',1,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),182,'recycling',1,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),182,'recycling',1,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),182,'recycling',1,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),182,'recycling',1,5);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),182,'recycling',1,6);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,6);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),235,'recycling',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),204,'recycling',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),235,'recycling',1,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),204,'recycling',1,5);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),204,'recycling',1,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),204,'recycling',1,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),204,'recycling',1,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),204,'recycling',1,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),204,'recycling',1,6);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),204,'recycling',1,8);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),218,'recycling',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),218,'recycling',1,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),218,'recycling',1,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),218,'recycling',1,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),218,'recycling',1,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),224,'recycling',1,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),224,'recycling',1,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),235,'recycling',1,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),224,'recycling',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),224,'recycling',1,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),224,'recycling',1,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),224,'recycling',1,6);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),224,'recycling',1,7);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),224,'recycling',1,8);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),224,'recycling',1,8);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),224,'recycling',1,9);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),235,'recycling',1,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),235,'recycling',1,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),235,'recycling',1,5);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),124,'recycling',1,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),124,'recycling',1,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,5);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'recycling',0,13);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),124,'recycling',1,0);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'donation',0,1);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'donation',0,2);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'donation',0,3);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'donation',0,4);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'donation',0,5);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),null,'donation',0,6);
INSERT INTO categories (created_at, parent_id, type, lvl, ordering) VALUES (now(),128,'recycling',1,12);
ALTER TABLE categories ENABLE TRIGGER ALL;

INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 1, 'en' , 'Furniture');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 2, 'en' , 'E-waste');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 3, 'en' , 'Appliances');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 4, 'en' , 'Mattresses');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 5, 'en' , 'Miscellaneous');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 6, 'en' , 'Trash removal');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 7, 'en' , 'Construction waste disposal');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 8, 'en' , 'Yard waste removal');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 9, 'en' , 'Loveseat');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 10, 'en' , 'Sofa/couch');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 11, 'en' , 'Sectional 2 or 3 piece');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 12, 'en' , 'Recliner');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 13, 'en' , 'Sleeper sofa');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 14, 'en' , 'Chairs');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 15, 'en' , 'Table');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 16, 'en' , 'Desk');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 17, 'en' , 'Bookcase');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 18, 'en' , 'Dresser');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 19, 'en' , 'Bed');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 20, 'en' , 'Take a part');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 21, 'en' , 'Computer');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 22, 'en' , 'Desktop printer');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 23, 'en' , 'Big printer');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 24, 'en' , 'TV');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 25, 'en' , 'Small');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 26, 'en' , 'Large');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 27, 'en' , 'Refrigerator');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 28, 'en' , 'Washer');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 29, 'en' , 'Dryer');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 30, 'en' , 'Stove');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 31, 'en' , 'Grill/bbq');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 32, 'en' , 'Small');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 33, 'en' , 'Standard');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 34, 'en' , 'Large');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 35, 'en' , 'Side by side');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 36, 'en' , 'Doors take of');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 37, 'en' , 'Twin');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 38, 'en' , 'Queen/king');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 39, 'en' , 'Box spring');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 127, 'en' , 'Used diapers');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 128, 'en' , 'Clothing');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 137, 'en' , 'Fish');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 139, 'en' , 'Fluorescent lights');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 140, 'en' , 'Batteries');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 141, 'en' , 'Poisons');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 142, 'en' , 'Pesticides');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 143, 'en' , 'Paint');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 144, 'en' , 'Expired medication');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 145, 'en' , 'Sharps');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 138, 'en' , 'Others');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 124, 'en' , 'Food waste');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 120, 'en' , 'Used Cooking Oil');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 119, 'en' , 'Used Motor Oil');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 125, 'en' , 'Used tires');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 129, 'en' , 'Used eyeglasses');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 130, 'en' , 'Frames');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 126, 'en' , 'Household Hazardous Waste');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 118, 'en' , 'Eyeglasses');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 214, 'en' , 'Automotive');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 236, 'en' , 'Aliminum');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 204, 'en' , 'Plastic');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 205, 'en' , '#1 PET (Beverage bottles)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 237, 'en' , 'Steel');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 211, 'en' , '#6 PS (vending cups)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 210, 'en' , '#5 PP (toys)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 212, 'en' , '#2 HDPE (milk jugs, detergent, shampoo bottles)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 208, 'en' , '#3 PVC (bubble foil)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 209, 'en' , '#4 LDPE (shopping bags)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 213, 'en' , '#7 Other plastic (acrylic, nylon)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 215, 'en' , 'scrap plastic pieces');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 216, 'en' , 'Aluminum cans CRV');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 217, 'en' , 'Bimetallic CRV beverage bottles');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 218, 'en' , 'Glass');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 219, 'en' , 'CRV beverage bottles');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 220, 'en' , 'Amber (brown glass)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 221, 'en' , 'Flint (clear glass)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 222, 'en' , 'Green');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 223, 'en' , '3-Mix glass');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 224, 'en' , 'Paper');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 227, 'en' , 'Newspaper');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 228, 'en' , 'Magazines');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 238, 'en' , 'Iron');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 225, 'en' , 'Cardboard (flattened)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 226, 'en' , 'Office paper');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 229, 'en' , 'Catalogs');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 231, 'en' , 'Ads');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 230, 'en' , 'Junk mail');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 233, 'en' , 'Books');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 232, 'en' , 'Paper bags');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 234, 'en' , 'Mixed paper');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 239, 'en' , 'Copper');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 240, 'en' , 'Brass');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 241, 'en' , 'Tin');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 242, 'en' , 'Used Coffee ground');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 243, 'en' , 'Eggshells');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 235, 'en' , 'Scrap Metal');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 249, 'en' , 'Cigarette butts');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 253, 'en' , 'Expired food');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 254, 'en' , 'Furniture');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 255, 'en' , 'Books');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 256, 'en' , 'Products');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 257, 'en' , 'Clothes');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 258, 'en' , 'Toys');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 259, 'en' , 'Other');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 250, 'en' , 'Shoes');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 1, 'ru' , 'Furniture');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 2, 'ru' , 'E-waste');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 3, 'ru' , 'Appliances');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 4, 'ru' , 'Mattresses');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 5, 'ru' , 'Miscellaneous');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 6, 'ru' , 'Trash removal');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 7, 'ru' , 'Construction waste disposal');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 8, 'ru' , 'Yard waste removal');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 9, 'ru' , 'Loveseat');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 10, 'ru' , 'Sofa/couch');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 11, 'ru' , 'Sectional 2 or 3 piece');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 12, 'ru' , 'Recliner');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 13, 'ru' , 'Sleeper sofa');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 14, 'ru' , 'Chairs');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 15, 'ru' , 'Table');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 16, 'ru' , 'Desk');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 17, 'ru' , 'Bookcase');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 18, 'ru' , 'Dresser');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 19, 'ru' , 'Bed');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 20, 'ru' , 'Take a part');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 21, 'ru' , 'Computer');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 22, 'ru' , 'Desktop printer');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 23, 'ru' , 'Big printer');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 24, 'ru' , 'TV');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 25, 'ru' , 'Small');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 26, 'ru' , 'Large');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 27, 'ru' , 'Refrigerator');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 28, 'ru' , 'Washer');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 29, 'ru' , 'Dryer');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 30, 'ru' , 'Stove');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 31, 'ru' , 'Grill/bbq');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 32, 'ru' , 'Small');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 33, 'ru' , 'Standard');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 34, 'ru' , 'Large');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 35, 'ru' , 'Side by side');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 36, 'ru' , 'Doors take of');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 37, 'ru' , 'Twin');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 38, 'ru' , 'Queen/king');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 39, 'ru' , 'Box spring');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 127, 'ru' , 'Used diapers');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 128, 'ru' , 'Clothing');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 137, 'ru' , 'Fish');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 139, 'ru' , 'Fluorescent lights');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 140, 'ru' , 'Batteries');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 141, 'ru' , 'Poisons');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 142, 'ru' , 'Pesticides');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 143, 'ru' , 'Paint');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 144, 'ru' , 'Expired medication');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 145, 'ru' , 'Sharps');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 138, 'ru' , 'Others');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 124, 'ru' , 'Food waste');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 120, 'ru' , 'Used Cooking Oil');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 119, 'ru' , 'Used Motor Oil');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 125, 'ru' , 'Used tires');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 129, 'ru' , 'Used eyeglasses');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 130, 'ru' , 'Frames');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 126, 'ru' , 'Household Hazardous Waste');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 118, 'ru' , 'Eyeglasses');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 214, 'ru' , 'Automotive');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 236, 'ru' , 'Aliminum');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 204, 'ru' , 'Plastic');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 205, 'ru' , '#1 PET (Beverage bottles)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 237, 'ru' , 'Steel');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 211, 'ru' , '#6 PS (vending cups)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 210, 'ru' , '#5 PP (toys)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 212, 'ru' , '#2 HDPE (milk jugs, detergent, shampoo bottles)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 208, 'ru' , '#3 PVC (bubble foil)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 209, 'ru' , '#4 LDPE (shopping bags)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 213, 'ru' , '#7 Other plastic (acrylic, nylon)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 215, 'ru' , 'scrap plastic pieces');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 216, 'ru' , 'Aluminum cans CRV');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 217, 'ru' , 'Bimetallic CRV beverage bottles');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 218, 'ru' , 'Glass');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 219, 'ru' , 'CRV beverage bottles');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 220, 'ru' , 'Amber (brown glass)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 221, 'ru' , 'Flint (clear glass)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 222, 'ru' , 'Green');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 223, 'ru' , '3-Mix glass');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 224, 'ru' , 'Paper');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 227, 'ru' , 'Newspaper');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 228, 'ru' , 'Magazines');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 238, 'ru' , 'Iron');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 225, 'ru' , 'Cardboard (flattened)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 226, 'ru' , 'Office paper');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 229, 'ru' , 'Catalogs');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 231, 'ru' , 'Ads');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 230, 'ru' , 'Junk mail');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 233, 'ru' , 'Books');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 232, 'ru' , 'Paper bags');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 234, 'ru' , 'Mixed paper');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 239, 'ru' , 'Copper');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 240, 'ru' , 'Brass');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 241, 'ru' , 'Tin');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 242, 'ru' , 'Used Coffee ground');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 243, 'ru' , 'Eggshells');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 235, 'ru' , 'Scrap Metal');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 253, 'ru' , 'Expired food');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 254, 'ru' , 'Furniture');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 255, 'ru' , 'Books');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 256, 'ru' , 'Products');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 257, 'ru' , 'Clothes');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 259, 'ru' , 'Other');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 250, 'ru' , 'Shoes');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 1, 'kz' , 'Furniture');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 2, 'kz' , 'E-waste');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 3, 'kz' , 'Appliances');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 4, 'kz' , 'Mattresses');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 5, 'kz' , 'Miscellaneous');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 6, 'kz' , 'Trash removal');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 7, 'kz' , 'Construction waste disposal');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 8, 'kz' , 'Yard waste removal');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 9, 'kz' , 'Loveseat');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 10, 'kz' , 'Sofa/couch');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 11, 'kz' , 'Sectional 2 or 3 piece');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 12, 'kz' , 'Recliner');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 13, 'kz' , 'Sleeper sofa');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 14, 'kz' , 'Chairs');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 15, 'kz' , 'Table');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 16, 'kz' , 'Desk');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 17, 'kz' , 'Bookcase');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 18, 'kz' , 'Dresser');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 19, 'kz' , 'Bed');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 20, 'kz' , 'Take a part');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 21, 'kz' , 'Computer');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 22, 'kz' , 'Desktop printer');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 23, 'kz' , 'Big printer');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 24, 'kz' , 'TV');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 25, 'kz' , 'Small');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 26, 'kz' , 'Large');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 27, 'kz' , 'Refrigerator');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 28, 'kz' , 'Washer');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 29, 'kz' , 'Dryer');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 30, 'kz' , 'Stove');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 31, 'kz' , 'Grill/bbq');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 32, 'kz' , 'Small');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 33, 'kz' , 'Standard');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 34, 'kz' , 'Large');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 35, 'kz' , 'Side by side');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 36, 'kz' , 'Doors take of');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 37, 'kz' , 'Twin');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 38, 'kz' , 'Queen/king');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 39, 'kz' , 'Box spring');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 127, 'kz' , 'Used diapers');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 128, 'kz' , 'Clothing');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 137, 'kz' , 'Fish');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 139, 'kz' , 'Fluorescent lights');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 140, 'kz' , 'Batteries');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 141, 'kz' , 'Poisons');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 142, 'kz' , 'Pesticides');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 143, 'kz' , 'Paint');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 144, 'kz' , 'Expired medication');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 145, 'kz' , 'Sharps');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 138, 'kz' , 'Others');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 124, 'kz' , 'Food waste');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 120, 'kz' , 'Used Cooking Oil');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 258, 'ru' , 'Игрушки');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 119, 'kz' , 'Used Motor Oil');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 125, 'kz' , 'Used tires');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 129, 'kz' , 'Used eyeglasses');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 130, 'kz' , 'Frames');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 126, 'kz' , 'Household Hazardous Waste');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 118, 'kz' , 'Eyeglasses');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 214, 'kz' , 'Automotive');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 236, 'kz' , 'Aliminum');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 204, 'kz' , 'Plastic');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 205, 'kz' , '#1 PET (Beverage bottles)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 237, 'kz' , 'Steel');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 211, 'kz' , '#6 PS (vending cups)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 210, 'kz' , '#5 PP (toys)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 212, 'kz' , '#2 HDPE (milk jugs, detergent, shampoo bottles)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 208, 'kz' , '#3 PVC (bubble foil)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 209, 'kz' , '#4 LDPE (shopping bags)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 213, 'kz' , '#7 Other plastic (acrylic, nylon)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 215, 'kz' , 'scrap plastic pieces');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 216, 'kz' , 'Aluminum cans CRV');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 217, 'kz' , 'Bimetallic CRV beverage bottles');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 218, 'kz' , 'Glass');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 219, 'kz' , 'CRV beverage bottles');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 220, 'kz' , 'Amber (brown glass)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 221, 'kz' , 'Flint (clear glass)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 222, 'kz' , 'Green');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 223, 'kz' , '3-Mix glass');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 224, 'kz' , 'Paper');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 227, 'kz' , 'Newspaper');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 228, 'kz' , 'Magazines');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 238, 'kz' , 'Iron');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 225, 'kz' , 'Cardboard (flattened)');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 226, 'kz' , 'Office paper');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 229, 'kz' , 'Catalogs');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 231, 'kz' , 'Ads');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 230, 'kz' , 'Junk mail');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 233, 'kz' , 'Books');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 232, 'kz' , 'Paper bags');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 234, 'kz' , 'Mixed paper');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 239, 'kz' , 'Copper');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 240, 'kz' , 'Brass');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 241, 'kz' , 'Tin');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 242, 'kz' , 'Used Coffee ground');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 243, 'kz' , 'Eggshells');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 235, 'kz' , 'Scrap Metal');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 249, 'kz' , 'Cigarette butts');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 253, 'kz' , 'Expired food');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 254, 'kz' , 'Furniture');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 255, 'kz' , 'Books');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 256, 'kz' , 'Products');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 257, 'kz' , 'Clothes');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 259, 'kz' , 'Other');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 250, 'kz' , 'Shoes');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 249, 'ru' , 'Сигаретные окурки');
INSERT INTO category_translations (created_at, category_id, locale, name) VALUES (now(), 258, 'kz' , 'Ойыншықтар');


ALTER TABLE geo_countries DISABLE TRIGGER ALL;
INSERT INTO geo_countries (created_at, currency) VALUES (now(), 'USD');
INSERT INTO geo_countries (created_at, currency) VALUES (now(), 'KZT');
INSERT INTO geo_countries (created_at, currency) VALUES (now(), 'RUB');
ALTER TABLE geo_countries ENABLE TRIGGER ALL;


INSERT INTO geo_country_translations (created_at, country_id, locale, name, alt_name) VALUES(now(),3,'en','Russia',null);
INSERT INTO geo_country_translations (created_at, country_id, locale, name, alt_name) VALUES(now(),2,'en','Kazakhstan',null);
INSERT INTO geo_country_translations (created_at, country_id, locale, name, alt_name) VALUES(now(),3,'ru','Россия',null);
INSERT INTO geo_country_translations (created_at, country_id, locale, name, alt_name) VALUES(now(),2,'ru','Казахстан',null);
INSERT INTO geo_country_translations (created_at, country_id, locale, name, alt_name) VALUES(now(),2,'kz','Қазақстан',null);
INSERT INTO geo_country_translations (created_at, country_id, locale, name, alt_name) VALUES(now(),3,'kz','Ресей',null);
INSERT INTO geo_country_translations (created_at, country_id, locale, name, alt_name) VALUES(now(),1,'ru','Соединенные Штаты Америки','США');
INSERT INTO geo_country_translations (created_at, country_id, locale, name, alt_name) VALUES(now(),1,'kz','Америка Құрама Штаттары','АҚШ');
INSERT INTO geo_country_translations (created_at, country_id, locale, name, alt_name) VALUES(now(),1,'en','United States of America','USA');
INSERT INTO geo_country_translations (created_at, country_id, locale, name, alt_name) VALUES(now(),1,'en','United States','US');
INSERT INTO geo_country_translations (created_at, country_id, locale, name, alt_name) VALUES(now(),1,'es','Estados Unidos','EU');
INSERT INTO geo_country_translations (created_at, country_id, locale, name, alt_name) VALUES(now(),3,'ru','Российская Федерация',null);

INSERT INTO units (created_at) VALUES (now()), (now()), (now()), (now());

INSERT INTO unit_translations (created_at, unit_id, locale, name) VALUES(now(),1,'en','kg');
INSERT INTO unit_translations (created_at, unit_id, locale, name) VALUES(now(),1,'kz','kg');
INSERT INTO unit_translations (created_at, unit_id, locale, name) VALUES(now(),1,'ru','kg');
INSERT INTO unit_translations (created_at, unit_id, locale, name) VALUES(now(),2,'en','L');
INSERT INTO unit_translations (created_at, unit_id, locale, name) VALUES(now(),2,'kz','L');
INSERT INTO unit_translations (created_at, unit_id, locale, name) VALUES(now(),2,'ru','L');
INSERT INTO unit_translations (created_at, unit_id, locale, name) VALUES(now(),3,'en','piece');
INSERT INTO unit_translations (created_at, unit_id, locale, name) VALUES(now(),3,'kz','piece');
INSERT INTO unit_translations (created_at, unit_id, locale, name) VALUES(now(),3,'ru','piece');
INSERT INTO unit_translations (created_at, unit_id, locale, name) VALUES(now(),4,'en','Tonna');
INSERT INTO unit_translations (created_at, unit_id, locale, name) VALUES(now(),4,'kz','Тонна');
INSERT INTO unit_translations (created_at, unit_id, locale, name) VALUES(now(),4,'ru','Тонна');