export const FETCH_CURRENT_USER_BEFORE = 'User/FETCH_CURRENT_USER_BEFORE';
export const FETCH_CURRENT_USER_SUCCESS = 'User/FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_FAILURE = 'User/FETCH_CURRENT_USER_FAILURE';

export const LOGIN_BEFORE = 'Login/LOGIN_BEFORE';
export const LOGIN_SUCCESS = 'Login/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'Login/LOGIN_FAILURE';
export const LOGIN_CREDENTIALS_CHANGED = 'Login/CREDENTIALS_CHANGED';
export const LOGIN_VALIDATE_REQUEST = 'Login/LOGIN_VALIDATE_REQUEST';
export const LOGIN_VALIDATE_SUCCESS = 'Login/LOGIN_VALIDATE_SUCCESS';
export const LOGIN_VALIDATE_FAILURE = 'Login/LOGIN_VALIDATE_FAILURE';
